In [2]:
import pandas as pd
import numpy as num
from matplotlib import pyplot as plt

In [2]:
data = pd.read_excel('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Data - Phase 1 Elements of Value - DRAFT copy.xlsx')

In [3]:
pd.set_option('display.max_columns', 25)
data.columns.tolist()

['Finished',
 'Date',
 'Response ID',
 'PID',
 'Gender',
 'Age',
 'Brand',
 'Other Android',
 'iPhone Model',
 'Older iPhone Model',
 'Samsung Model',
 'Other Samsung Model',
 'Google Model',
 'Other Google Model',
 'Other Android Model',
 'List Price',
 'Slate + Accessory',
 'Slate Large Display',
 'Slate Medium Display',
 'Slate Small Display',
 'Book Inner Panels',
 'Wallet Format',
 'Book Outer Panels',
 'Book 3 Panels',
 'Book Sliding Display',
 'Top Slate + Accessory',
 'Top Slate Large Display',
 'Top Slate Medium Display',
 'Top Slate Small Display',
 'Top Book Inner Panels',
 'Top Wallet Format',
 'Top Book Outer Panels',
 'Top Book 3 Panels',
 'Top Book Sliding Display',
 'Preferred Brand',
 'Other Preferred Brand',
 'Loyalty',
 'Loyalty Proud',
 'Loyalty Promoter',
 'Loyalty Recommend',
 'Next Cost',
 'Tier',
 'Latest premium (over $600)',
 'Latest ultra-premium (over $1,200)',
 'Lite or Essential premium smartphones',
 'Latest mid-tier  ($300 and $600)',
 'Latest budget or value  (under $300)',
 'Earlier generation premium',
 'Earlier generation mid-tier',
 'Earlier generation budget',
 'Used',
 'Cheap',
 'Good Deal',
 'Getting Expensive',
 'Too Expensive',
 'Buy Deal',
 'Buy Getting Expensive',
 'Current Staisfaction',
 'Current Saves Time',
 'Current Simplifies',
 'Current Makes Money',
 'Current Reduce Risk',
 'Current Organizes',
 'Current Integrates',
 'Current Connects',
 'Current Reduce Effort',
 'Current Avoid Hassles',
 'Current Reduce Cost',
 'Current Quality',
 'Current Variety',
 'Current Senses',
 'Current Informs',
 'Current Reduce Anxiety',
 'Current Rewards',
 'Current Nostalgia',
 'Current Aesthetics',
 'Current Badge Value',
 'Current Wellness',
 'Current Therapeutic',
 'Current Fun',
 'Current Attractiveness',
 'Current Access',
 'Current Transcendence',
 'Current Hope',
 'Current Actualization',
 'Current Motivates',
 'Current Heirloom',
 'Current Belonging',
 'Current Saves Time Rate',
 'Current Simplifies Rate',
 'Current Makes Money Rate',
 'Current Reduce Risk Rate',
 'Current Organizes Rate',
 'Current Integrates  Rate',
 'Current Connects Rate',
 'Current Reduce Effort Rate',
 'Current Avoid Hassles Rate',
 'Current Reduce Cost Rate',
 'Current Quality Rate',
 'Current Variety Rate',
 'Current Senses Rate',
 'Current Informs Rate',
 'Current Reduce Anxiety Rate',
 'Current Rewards Rate',
 'Current Nostalgia Rate',
 'Current Aesthetics Rate',
 'Current Badge Value Rate',
 'Current Wellness Rate',
 'Current Therapeutic Rate',
 'Current Fun Rate',
 'Current Attractiveness Rate',
 'Current Access Rate',
 'Current Transcendence Rate',
 'Current Hope Rate',
 'Current Actualization Rate',
 'Current Motivates Rate',
 'Current Heirloom Rate',
 'Current Belonging Rate',
 'Voice or Video calls, Messaging, Email',
 'Taking Pictures or Videos',
 'Streaming Video',
 'Streaming Music',
 'Playing Games',
 'Productivity tools',
 'Health/Fitness',
 'Smart Home Control',
 'Internet Browsing',
 'Shopping / Coupon Apps',
 'Mobile Wallet / Pay',
 'Voice Assistant',
 'Navigation & Maps',
 'Device Tracking',
 'Family / Personal Security',
 'Social Media',
 'Third-party & Carrier Preloads',
 'Connectivity with PC/Laptop, Tablet',
 'Usage with Earbuds/Headphones',
 'Usage with Smart Watches, Fitness Bands',
 'Augmented Reality / Virtual Reality',
 'Cloud storage',
 'Personalizing phone content',
 'Voice or Video calls, Messaging, Email Rate Rate',
 'Taking Pictures or Videos Rate',
 'Streaming Video Rate',
 'Streaming Music Rate',
 'Playing Games Rate',
 'Productivity tools Rate',
 'Health/Fitness Rate',
 'Smart Home Control Rate',
 'Internet Browsing Rate',
 'Shopping / Coupon Apps Rate',
 'Mobile Wallet / Pay Rate',
 'Voice Assistant Rate',
 'Navigation & Maps Rate',
 'Device Tracking Rate',
 'Family / Personal Security Rate',
 'Social Media Rate',
 'Third-party & Carrier Preloads Rate',
 'Connectivity with PC/Laptop, Tablet Rate',
 'Usage with Earbuds/Headphones Rate',
 'Usage with Smart Watches, Fitness Bands Rate',
 'Augmented Reality / Virtual Reality Rate',
 'Cloud storage Rate',
 'Personalizing phone content Rate',
 'Current Size',
 'Current Shape',
 'Current Buttons',
 'Current Chassis Material',
 'Current Color Choices',
 'Current Look and Feel',
 'Current Aspect Ratio',
 'Current Display Color',
 'Current Refresh Rate',
 'Current Camera',
 'Current Battery Capacity',
 'Current Waterproof / Dust proof',
 'Current Wireless Charging',
 'Current Fast Charging',
 'Current Touch and Screen Responsiveness',
 'Current Storage Capacity',
 'Current General User Interface',
 'Current Support for one-hand use',
 'Current Consistent usability',
 'Current Pakcaging',
 'Default  phone app rate',
 'Other voice call rate',
 'Other voice app',
 'Voice Call Saves Time',
 'Voice Call Simplifies',
 'Voice Call Makes Money',
 'Voice Call Reduce Risk',
 'Voice Call Organizes',
 'Voice Call Integrates',
 'Voice Call Connects',
 'Voice Call Reduce Effort',
 'Voice Call Avoid Hassles',
 'Voice Call Reduce Cost',
 'Voice Call Quality',
 'Voice Call Variety',
 'Voice Call Senses',
 'Voice Call Informs',
 'Voice Call Reduce Anxiety',
 'Voice Call Rewards',
 'Voice Call Nostalgia',
 'Voice Call Aesthetics',
 'Voice Call Badge Value',
 'Voice Call Wellness',
 'Voice Call Therapeutic',
 'Voice Call Fun',
 'Voice Call Attractiveness',
 'Voice Call Access',
 'Voice Call Transcendence',
 'Voice Call Hope',
 'Voice Call Actualization',
 'Voice Call Motivates',
 'Voice Call Heirloom',
 'Voice Call Belonging',
 'Face Time rate',
 'Default video call app rate',
 'Google Duo rate',
 'Skype rate',
 'Facebook Messenger video rate',
 'Whatsapp video rate',
 'Zoom rate',
 'Other video app rate',
 'Other video apps',
 'Video Call Saves Time',
 'Video Call Simplifies',
 'Video Call Makes Money',
 'Video Call Reduce Risk',
 'Video Call Organizes',
 'Video Call Integrates',
 'Video Call Connects',
 'Video Call Reduce Effort',
 'Video Call Avoid Hassles',
 'Video Call Reduce Cost',
 'Video Call Quality',
 'Video Call Variety',
 'Video Call Senses',
 'Video Call Informs',
 'Video Call Reduce Anxiety',
 'Video Call Rewards',
 'Video Call Nostalgia',
 'Video Call Aesthetics',
 'Video Call Badge Value',
 'Video Call Wellness',
 'Video Call Therapeutic',
 'Video Call Fun',
 'Video Call Attractiveness',
 'Video Call Access',
 'Video Call Transcendence',
 'Video Call Hope',
 'Video Call Actualization',
 'Video Call Motivates',
 'Video Call Heirloom',
 'Video Call Belonging',
 'Multi-Person Video Call',
 'iMessage rate',
 'Default messaging app rate',
 'Facebook Messenger rate',
 'Whatsapp rate',
 'Snapchat rate',
 'Other messaging rate',
 'Other Messaging Apps',
 'Messaging Saves Time',
 'Messaging Simplifies',
 'Messaging Makes Money',
 'Messaging Reduce Risk',
 'Messaging Organizes',
 'Messaging Integrates',
 'Messaging Connects',
 'Messaging Reduce Effort',
 'Messaging Avoid Hassles',
 'Messaging Reduce Cost',
 'Messaging Quality',
 'Messaging Variety',
 'Messaging Senses',
 'Messaging Informs',
 'Messaging Reduce Anxiety',
 'Messaging Rewards',
 'Messaging Nostalgia',
 'Messaging Aesthetics',
 'Messaging Badge Value',
 'Messaging Wellness',
 'Messaging Therapeutic',
 'Messaging Fun',
 'Messaging Attractiveness',
 'Messaging Access',
 'Messaging Transcendence',
 'Messaging Hope',
 'Messaging Actualization',
 'Messaging Motivates',
 'Messaging Heirloom',
 'Messaging Belonging',
 'RCS',
 'Default Apple Mail rate',
 'Default Email rate',
 'Gmail rate',
 'Microsoft Outlook or Hotmail rate',
 'Yahoo Mail rate',
 'Other email rate',
 'Other Email Apps',
 'Email Saves Time',
 'Email Simplifies',
 'Email Makes Money',
 'Email Reduce Risk',
 'Email Organizes',
 'Email Integrates',
 'Email Connects',
 'Email Reduce Effort',
 'Email Avoid Hassles',
 'Email Reduce Cost',
 'Email Quality',
 'Email Variety',
 'Email Senses',
 'Email Informs',
 'Email Reduce Anxiety',
 'Email Rewards',
 'Email Nostalgia',
 'Email Aesthetics',
 'Email Badge Value',
 'Email Wellness',
 'Email Therapeutic',
 'Email Fun',
 'Email Attractiveness',
 'Email Access',
 'Email Transcendence',
 'Email Hope',
 'Email Actualization',
 'Email Motivates',
 'Email Heirloom',
 'Email Belonging',
 'Safari rate',
 'Samsung Internet rate',
 'Chrome rate',
 'Edge rate',
 'Firefox rate',
 'Other internet rate',
 'Other Internet Apps',
 'Internet Saves Time',
 'Internet Simplifies',
 'Internet Makes Money',
 'Internet Reduce Risk',
 'Internet Organizes',
 'Internet Integrates',
 'Internet Connects',
 'Internet Reduce Effort',
 'Internet Avoid Hassles',
 'Internet Reduce Cost',
 'Internet Quality',
 'Internet Variety',
 'Internet Senses',
 'Internet Informs',
 'Internet Reduce Anxiety',
 'Internet Rewards',
 'Internet Nostalgia',
 'Internet Aesthetics',
 'Internet Badge Value',
 'Internet Wellness',
 'Internet Therapeutic',
 'Internet Fun',
 'Internet Attractiveness',
 'Internet Access',
 'Internet Transcendence',
 'Internet Hope',
 'Internet Actualization',
 'Internet Motivates',
 'Internet Heirloom',
 'Internet Belonging',
 'Facebook rate',
 'Instagram rate',
 'Pinterest rate',
 'SnapChat social rate',
 'LinkedIn rate',
 'Twitter rate',
 'Discord rate',
 'Reddit rate',
 'Yelp rate',
 'Whatspp rate',
 'Tumblr rate',
 'TikTok rate',
 'Other Social Media rate',
 'Other Social Media Apps',
 'Social Saves Time',
 'Social Simplifies',
 'Social Makes Money',
 'Social Reduce Risk',
 'Social Organizes',
 'Social Integrates',
 'Social Connects',
 'Social Reduce Effort',
 'Social Avoid Hassles',
 'Social Reduce Cost',
 'Social Quality',
 'Social Variety',
 'Social Senses',
 'Social Informs',
 'Social Reduce Anxiety',
 'Social Rewards',
 'Social Nostalgia',
 'Social Aesthetics',
 'Social Badge Value',
 'Social Wellness',
 'Social Therapeutic',
 'Social Fun',
 'Social Attractiveness',
 'Social Access',
 'Social Transcendence',
 'Social Hope',
 'Social Actualization',
 'Social Motivates',
 'Social Heirloom',
 'Social Belonging',
 'Rear camera (standard) rate',
 'Rear camera (wide-angle or ultra wide angle) rate',
 'Rear camera (telephoto) rate',
 'Selfie camera (standard) rate',
 'Selfie camera (wide angle or group) rate',
 'Portrait, Live Focus or Bokeh (blurring of background) rate',
 'Night Mode Performance rate',
 'Zoom (Optical, Hybrid and Digital) rate',
 'Macro (closeup) rate',
 'Filters, Special Effects (e.g., Fun AR stickers, Panorama..) rate',
 'Multiple cameras at the same time rate',
 'Other camera feature rate',
 'Other Camera Features',
 'Camera Saves Time',
 'Camera Simplifies',
 'Camera Makes Money',
 'Camera Reduce Risk',
 'Camera Organizes',
 'Camera Integrates',
 'Camera Connects',
 'Camera Reduce Effort',
 'Camera Avoid Hassles',
 'Camera Reduce Cost',
 'Camera Quality',
 'Camera Variety',
 'Camera Senses',
 'Camera Informs',
 'Camera Reduce Anxiety',
 'Camera Rewards',
 'Camera Nostalgia',
 'Camera Aesthetics',
 'Camera Badge Value',
 'Camera Wellness',
 'Camera Therapeutic',
 'Camera Fun',
 'Camera Attractiveness',
 'Camera Access',
 'Camera Transcendence',
 'Camera Hope',
 'Camera Actualization',
 'Camera Motivates',
 'Camera Heirloom',
 'Camera Belonging',
 'Video Portrait, Live Focus or Bokeh rate',
 'Slow motion rate',
 'Time Lapse / HyperLapse rate',
 'Video Night Mode Performance rate',
 'Multiple Cameras Video rate',
 'Video: HD rate',
 'Video: 4K rate',
 'Attention 1',
 'Optical or DIgital Stabilization rate',
 'Video Special Effects rate',
 'Other Video Camera Features rate',
 'Other video camera features',
 'Camcorder Saves Time',
 'Camcorder Simplifies',
 'Camcorder Makes Money',
 'Camcorder Reduce Risk',
 'Camcorder Organizes',
 'Camcorder Integrates',
 'Camcorder Connects',
 'Camcorder Reduce Effort',
 'Camcorder Avoid Hassles',
 'Camcorder Reduce Cost',
 'Camcorder Quality',
 'Camcorder Variety',
 'Camcorder Senses',
 'Camcorder Informs',
 'Camcorder Reduce Anxiety',
 'Camcorder Rewards',
 'Camcorder Nostalgia',
 'Camcorder Aesthetics',
 'Camcorder Badge Value',
 'Camcorder Wellness',
 'Camcorder Therapeutic',
 'Camcorder Fun',
 'Camcorder Attractiveness',
 'Camcorder Access',
 'Camcorder Transcendence',
 'Camcorder Hope',
 'Camcorder Actualization',
 'Camcorder Motivates',
 'Camcorder Heirloom',
 'Camcorder Belonging',
 'Photos (Apple) rate',
 'Gallery (Samsung) rate',
 'Google Photos rate',
 'Lightroom rate',
 'Adobe Photoshop Express rate',
 'Snapseed rate',
 'VSCO rate',
 'Other photo storage rate',
 'Other photo storage apps',
 'Photo Storage Saves Time',
 'Photo Storage Simplifies',
 'Photo Storage Makes Money',
 'Photo Storage Reduce Risk',
 'Photo Storage Organizes',
 'Photo Storage Integrates',
 'Photo Storage Connects',
 'Photo Storage Reduce Effort',
 'Photo Storage Avoid Hassles',
 'Photo Storage Reduce Cost',
 'Photo Storage Quality',
 'Photo Storage Variety',
 'Photo Storage Senses',
 'Photo Storage Informs',
 'Photo Storage Reduce Anxiety',
 'Photo Storage Rewards',
 'Photo Storage Nostalgia',
 'Photo Storage Aesthetics',
 'Photo Storage Badge Value',
 'Photo Storage Wellness',
 'Photo Storage Therapeutic',
 'Photo Storage Fun',
 'Photo Storage Attractiveness',
 'Photo Storage Access',
 'Photo Storage Transcendence',
 'Photo Storage Hope',
 'Photo Storage Actualization',
 'Photo Storage Motivates',
 'Photo Storage Heirloom',
 'Photo Storage Belonging',
 'Photo Transfer Method',
 'Apple Arcade rate',
 'Google Play Game Subscription rate',
 'Google Stadia Cloud Gaming Subscription rate',
 'Nvidia Cloud Gaming Subscription rate',
 'Microsoft Xbox Subscription rate',
 'Sony Playstation Online Subscription rate',
 'Play Preloaded games Only rate',
 'Play Preloaded games and downloaded games, no subscription rate',
 'Other Gaming App rate',
 'Other Gaming Apps',
 'Gaming Saves Time',
 'Gaming Simplifies',
 'Gaming Makes Money',
 'Gaming Reduce Risk',
 'Gaming Organizes',
 'Gaming Integrates',
 'Gaming Connects',
 'Gaming Reduce Effort',
 'Gaming Avoid Hassles',
 'Gaming Reduce Cost',
 'Gaming Quality',
 'Gaming Variety',
 'Gaming Senses',
 'Gaming Informs',
 'Gaming Reduce Anxiety',
 'Gaming Rewards',
 'Gaming Nostalgia',
 'Gaming Aesthetics',
 'Gaming Badge Value',
 'Gaming Wellness',
 'Gaming Therapeutic',
 'Gaming Fun',
 'Gaming Attractiveness',
 'Gaming Access',
 'Gaming Transcendence',
 'Gaming Hope',
 'Gaming Actualization',
 'Gaming Motivates',
 'Gaming Heirloom',
 'Gaming Belonging',
 'Apple Music Paid',
 'YouTube Music Paid',
 'Spotify Paid',
 'Pandora Paid',
 'iHeartRadio Paid',
 'Tidal Paid',
 'Amazon Music Paid',
 'Google Play Music Paid',
 'Other Music Subscription Paid',
 'Other Music Subscription Apps',
 'Apple Music rate',
 'YouTube Music rate',
 'Spotify rate',
 'Pandora rate',
 'iHeartRadio rate',
 'Tidal rate',
 'Amazon Music rate',
 'Google Play Music rate',
 'Other Music Subscription rate',
 'Other Music Subscription Apps 2',
 'Music Saves Time',
 'Music Simplifies',
 'Music Makes Money',
 'Music Reduce Risk',
 'Music Organizes',
 'Music Integrates',
 'Music Connects',
 'Music Reduce Effort',
 'Music Avoid Hassles',
 'Music Reduce Cost',
 'Music Quality',
 'Music Variety',
 'Music Senses',
 'Music Informs',
 'Music Reduce Anxiety',
 'Music Rewards',
 'Gaming Nostalgia2',
 'Music Aesthetics',
 'Music Badge Value',
 'Music Wellness',
 'Music Therapeutic',
 'Music Fun',
 'Music Attractiveness',
 'Music Access',
 'Music Transcendence',
 'Music Hope',
 'Music Actualization',
 'Music Motivates',
 'Music Heirloom',
 'Music Belonging',
 'Apple TV+ Paid',
 'Amazon Prime Video Paid',
 'Disney+ Paid',
 'Netflix Paid',
 'Hulu Paid',
 'CBS All Access Paid',
 'HBO Now or HBO MAX Paid',
 'NBC Peacock Service Paid',
 'YouTube TV Premium Paid',
 'Sling TV Paid',
 'Fubo TV Paid',
 'Philo Paid',
 'Quibi Paid',
 'Other Video Streaming Paid',
 'Other Video Streaming Apps',
 'Apple TV+ rate',
 'Amazon Prime Video rate',
 'Disney+ rate',
 'Netflix rate',
 'Hulu rate',
 'CBS All Access rate',
 'HBO Now or HBO MAX rate',
 'NBC Peacock Service rate',
 'YouTube TV Premium rate',
 'Sling TV rate',
 'Fubo TV rate',
 'Philo rate',
 'Quibi rate',
 'Other Video Streaming rate',
 'Other Video Streaming Apps 2',
 'Paid Video Streaming Saves Time',
 'Paid Video Streaming Simplifies',
 'Paid Video Streaming Makes Money',
 'Paid Video Streaming Reduce Risk',
 'Paid Video Streaming Organizes',
 'Paid Video Streaming Integrates',
 'Paid Video Streaming Connects',
 'Paid Video Streaming Reduce Effort',
 'Paid Video Streaming Avoid Hassles',
 'Paid Video Streaming Reduce Cost',
 'Paid Video Streaming Quality',
 'Paid Video Streaming Variety',
 'Paid Video Streaming Senses',
 'Paid Video Streaming Informs',
 'Paid Video Streaming Reduce Anxiety',
 'Paid Video Streaming Rewards',
 'Paid Video Streaming Nostalgia',
 'Paid Video Streaming Aesthetics',
 'Paid Video Streaming Badge Value',
 'Paid Video Streaming Wellness',
 'Paid Video Streaming Therapeutic',
 'Paid Video Streaming Fun',
 'Paid Video Streaming Attractiveness',
 'Paid Video Streaming Access',
 'Paid Video Streaming Transcendence',
 'Paid Video Streaming Hope',
 'Paid Video Streaming Actualization',
 'Paid Video Streaming Motivates',
 'Paid Video Streaming Heirloom',
 'Paid Video Streaming Belonging',
 'Crackle rate',
 'Vudu rate',
 'Roku Channel rate',
 'Pluto TV rate',
 'IMDb rate',
 'YouTube rate',
 'Tubi rate',
 'Twitch rate',
 'XUMO rate',
 'Attention 2',
 'Other Free Video Streaming Rate',
 'Other Free Video Streaming Apps',
 'Free Video Streaming Saves Time',
 'Free Video Streaming Simplifies',
 'Free Video Streaming Makes Money',
 'Free Video Streaming Reduce Risk',
 'Free Video Streaming Organizes',
 'Free Video Streaming Integrates',
 'Free Video Streaming Connects',
 'Free Video Streaming Reduce Effort',
 'Free Video Streaming Avoid Hassles',
 'Free Video Streaming Reduce Cost',
 'Free Video Streaming Quality',
 'Free Video Streaming Variety',
 'Free Video Streaming Senses',
 'Free Video Streaming Informs',
 'Free Video Streaming Reduce Anxiety',
 'Free Video Streaming Rewards',
 'Free Video Streaming Nostalgia',
 'Free Video Streaming Aesthetics',
 'Free Video Streaming Badge Value',
 'Free Video Streaming Wellness',
 'Free Video Streaming Therapeutic',
 'Free Video Streaming Fun',
 'Free Video Streaming Attractiveness',
 'Free Video Streaming Access',
 'Free Video Streaming Transcendence',
 'Free Video Streaming Hope',
 'Free Video Streaming Actualization',
 'Free Video Streaming Motivates',
 'Free Video Streaming Heirloom',
 'Free Video Streaming Belonging',
 'Apple Pay rate',
 'Samsung Pay rate',
 'Google Pay rate',
 'Fitbit Pay rate',
 'Garmin Pay rate',
 'LG Pay rate',
 'Other Mobile Pay rate',
 'Other Mobile Pay Apps',
 'Mobile Pay Saves Time',
 'Mobile Pay Simplifies',
 'Mobile Pay Makes Money',
 'Mobile Pay Reduce Risk',
 'Mobile Pay Organizes',
 'Mobile Pay Integrates',
 'Mobile Pay Connects',
 'Mobile Pay Reduce Effort',
 'Mobile Pay Avoid Hassles',
 'Mobile Pay Reduce Cost',
 'Mobile Pay Quality',
 'Mobile Pay Variety',
 'Mobile Pay Senses',
 'Mobile Pay Informs',
 'Mobile Pay Reduce Anxiety',
 'Mobile Pay Rewards',
 'Mobile Pay Nostalgia',
 'Mobile Pay Aesthetics',
 'Mobile Pay Badge Value',
 'Mobile Pay Wellness',
 'Mobile Pay Therapeutic',
 'Mobile Pay Fun',
 'Mobile Pay Attractiveness',
 'Mobile Pay Access',
 'Mobile Pay Transcendence',
 'Mobile Pay Hope',
 'Mobile Pay Actualization',
 'Mobile Pay Motivates',
 'Mobile PayHeirloom',
 'Mobile Pay Belonging',
 'Apple Health rate',
 'Samsung Health rate',
 'Google Fit rate',
 'MyFitnessPal rate',
 'Fitbit Coach rate',
 'Peloton rate',
 'Strava rate',
 'Other Health App rate',
 'Other Health Apps',
 'Health Saves Time',
 'Health Simplifies',
 'Health Makes Money',
 'Health Reduce Risk',
 'Health Organizes',
 'HealthIntegrates',
 'Health Connects',
 'Health Reduce Effort',
 'Health Avoid Hassles',
 'Health Reduce Cost',
 'Health Quality',
 'Health Variety',
 'Health Senses',
 'Health Informs',
 'Health Anxiety',
 'Health Rewards',
 'Health Nostalgia',
 'Health Aesthetics',
 'Health Badge Value',
 'Health Wellness',
 'Health Therapeutic',
 'Health Fun',

In [4]:
data['Gender']

0         Male
1         Male
2       Female
3       Female
4         Male
         ...
1051      Male
1052      Male
1053      Male
1054      Male
1055      Male
Name: Gender, Length: 1056, dtype: object

## 1056 Participants

In [5]:
data[data['Gender']=='Male']

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
0,True,2020-07-20 09:45:09,R_aXmDmwWggyyauot,P01,Male,25-34,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single without children,"$75,000-$99,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,NaN
1,True,2020-07-20 09:45:09,R_2n4mDypHvVcry9T,P02,Male,35-44,Google,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Masters / Post-graduate certification,NaN,Employed full-time,"Handlers, Equipment Cleaners, Helpers, and Lab...",NaN,Expressers,NaN
4,True,2020-07-20 09:45:09,R_41scVuzu1NVb66h,P05,Male,35-44,Google,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Prefer not to answer,NaN,Prefer not to answer,NaN,NaN,Expressers,NaN
8,True,2020-07-20 09:45:09,R_8Jj9vcoo6IiDqaV,P09,Male,25-34,LG,NaN,NaN,NaN,NaN,NaN,...,NaN,Others (please specify),NaN,Single without children,"Less than $15,000",Graduated 2-year college or technical school,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,1.0
10,True,2020-07-20 09:45:09,R_3DzTBGPU2XaSEhD,P11,Male,Under 18,Apple,NaN,iPhone 11 Pro Max,NaN,NaN,NaN,...,NaN,Sprint,NaN,Prefer not to answer,"Less than $15,000",Attended or currently attending 4-year university,NaN,Employed part-time,NaN,NaN,Productives,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,True,2020-07-20 09:45:17,R_26uJWCE8tWNTCBf,P1052,Male,25-34,Samsung,NaN,NaN,NaN,Other model (please specify model),s9+,...,NaN,Verizon,NaN,Single without children,"$35,000-$49,999",Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
1052,True,2020-07-20 09:45:17,R_9G3Ut4u09W4CWRD,P1053,Male,35-44,Samsung,NaN,NaN,NaN,A series (please specify model),galxger J3,...,NaN,Others (please specify),Straight talk,Single without children,"$25,000-$34,999",Graduated 4-year university,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Productives,1.0
1053,True,2020-07-20 09:45:17,R_6tiXdlFMoOUJprL,P1054,Male,45-54,Samsung,NaN,NaN,NaN,Other model (please specify model),Samsung Galaxy S9,...,NaN,AT&T,NaN,Married with children,"$75,000-$99,999",Graduated 4-year university,NaN,Employed full-time,"Machine Operators, Assemblers, and Inspectors",NaN,Productives,1.0
1054,True,2020-07-20 09:45:17,R_eUV7IyASFyS5EO1,P1055,Male,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),S9,...,NaN,Verizon,NaN,Single with children,"$150,000-$199,999","Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,1.0
1055,True,2020-07-20 09:45:17,R_5C2BmnIi0OOLJAx,P1056,Male,35-44,Samsung,NaN,NaN,NaN,S10 Plus,NaN,...,NaN,AT&T,NaN,Married with children,"$100,000-$149,999",Masters / Post-graduate certification,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Expressers,1.0

## There are 494 males

In [6]:
data[data['Gender']=='Female']

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
2,False,2020-07-20 09:45:09,R_0faxTabFs6vw4xT,P03,Female,25-34,Samsung,NaN,NaN,NaN,Note 10+,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,True,2020-07-20 09:45:09,R_2shSLWBLzfglhJj,P04,Female,25-34,Google,NaN,NaN,NaN,NaN,NaN,...,NaN,AT&T,NaN,Life partner without children,Prefer not to answer,"Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,NaN
5,True,2020-07-20 09:45:09,R_3EEkYkv5mbzboFL,P06,Female,25-34,Apple,NaN,Older Model (please enter model name),iPhone 6S,NaN,NaN,...,NaN,AT&T,NaN,Single without children,Prefer not to answer,Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Traditionalists,NaN
6,True,2020-07-20 09:45:09,R_6YdUBuksDEwG9CJ,P07,Female,18-24,Apple,NaN,iPhone 11 Pro Max,NaN,NaN,NaN,...,NaN,Verizon,NaN,Life partner without children,"$200,000 or more",Graduated 4-year university,NaN,Prefer not to answer,"Precision, Production, Craft, and Repair Occup...",NaN,Productives,1.0
7,True,2020-07-20 09:45:09,R_bl2zGnfrxGjh4Mt,P08,Female,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),Halo,...,NaN,Others (please specify),Cricket,Single with children,"Less than $15,000",Graduated high School,NaN,Homemaker or not working by choice,NaN,NaN,Social Savvies,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
948,True,2020-07-20 09:45:16,R_3K0lPKm8sPPKYaV,P949,Female,25-34,Apple,NaN,iPhone XS Max,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Single without children,"$35,000-$49,999",Graduated 4-year university,NaN,Employed full-time,Service Occupations,NaN,Expressers,1.0
950,True,2020-07-20 09:45:16,R_eV6VDvCLkZjiCbP,P951,Female,45-54,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single with children,"Less than $15,000",Attended or currently attending 2-year college...,NaN,Not employed,Other (please specify),Don‚Äôt work,Social Savvies,1.0
951,True,2020-07-20 09:45:16,R_2reDFiBxIAtraZf,P952,Female,25-34,Apple,NaN,iPhone 8 Plus,NaN,NaN,NaN,...,NaN,Others (please specify),Straight Talk,Single without children,"$15,000-$24,999",Graduated high School,NaN,Employed full-time,Administrative Support Occupations,NaN,Expressers,1.0
952,True,2020-07-20 09:45:16,R_9ylHMTZUPb4FDNz,P953,Female,25-34,Apple,NaN,Older Model (please enter model name),iPhone 7,NaN,NaN,...,NaN,AT&T,NaN,Married with children,"$100,000-$149,999",Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Browsers,1.0
1002,True,2020-07-20 09:45:17,R_5aPqqcwCllAwxU1,P1003,Female,18-24,Samsung,NaN,NaN,NaN,S10 Plus,NaN,...,NaN,Verizon,NaN,Single without children,"$25,000-$34,999",Graduated 4-year university,NaN,Employed full-time,Sales Occupations,NaN,NaN,1.0

## There are 562 Females

In [7]:
data['Household Income']

0            $75,000-$99,999
1       Prefer not to answer
2                        NaN
3       Prefer not to answer
4       Prefer not to answer
                ...
1051         $35,000-$49,999
1052         $25,000-$34,999
1053         $75,000-$99,999
1054       $150,000-$199,999
1055       $100,000-$149,999
Name: Household Income, Length: 1056, dtype: object

In [8]:
data['Household Income'].unique()

array(['$75,000-$99,999', 'Prefer not to answer', nan, '$200,000 or more',
       'Less than $15,000', '$100,000-$149,999', '$150,000-$199,999',
       '$50,000-$74,999', '$25,000-$34,999', '$35,000-$49,999',
       '$15,000-$24,999'], dtype=object)

There are some columns where the participant did not answer, or there is no value. We need to clean this up, and we need to adjust or n accordingly.

In [9]:
data.loc[pd.isna(data["Household Income"]), :].index

Int64Index([2], dtype='int64')

In [10]:
data.iloc[2]['Household Income']

nan

The 3rd person has a nan value.

In [11]:
data.iloc[2]['Household Income']

nan

her PID is P03

In [12]:
pd.value_counts(data['Household Income'].values)

$50,000-$74,999         197
$35,000-$49,999         155
$25,000-$34,999         126
$75,000-$99,999         113
$100,000-$149,999       107
Less than $15,000        95
$15,000-$24,999          91
$150,000-$199,999        83
$200,000 or more         63
Prefer not to answer     25
dtype: int64

## All the Household Incomes above

In [13]:
data['Education'].unique()

array(['Masters / Post-graduate certification', nan,
       'Ph.D. or professional degrees (M.D., J.D.)',
       'Prefer not to answer', 'Graduated 4-year university',
       'Graduated high School',
       'Graduated 2-year college or technical school',
       'Attended or currently attending 4-year university',
       'Attended or currently attending 2-year college or technical school',
       'Attended or currently attending high School',
       'Other - please specify:'], dtype=object)

We need to the do the same thing for education as we did for household income.

In [14]:
data.loc[pd.isna(data["Education"]), :].index

Int64Index([2], dtype='int64')

It seems as though though the third person didn't finish much of their survey.

In [15]:
pd.value_counts(data['Education'].values)

Graduated 4-year university                                           275
Graduated high School                                                 231
Masters / Post-graduate certification                                 142
Attended or currently attending 2-year college or technical school    116
Graduated 2-year college or technical school                          113
Attended or currently attending 4-year university                      92
Ph.D. or professional degrees (M.D., J.D.)                             45
Attended or currently attending high School                            19
Other - please specify:                                                14
Prefer not to answer                                                    8
dtype: int64

## All the Education Levels above

In [16]:
data['Ethnicity'].unique()

array(['East Asian / South East  / South Asian', 'White / Caucasian', nan,
       'Prefer not to answer', 'Black or  African American',
       'Hispanic / Latino', 'Native Hawaiian / Pacific Islander',
       'Other - please specify:',
       'American Indian / Alaskan / Native American'], dtype=object)

In [17]:
data.loc[pd.isna(data["Ethnicity"]), :].index

Int64Index([2], dtype='int64')

In [18]:
pd.value_counts(data['Ethnicity'].values)

White / Caucasian                              747
Black or  African American                     117
Hispanic / Latino                               82
East Asian / South East  / South Asian          74
Other - please specify:                         14
American Indian / Alaskan / Native American     11
Prefer not to answer                             7
Native Hawaiian / Pacific Islander               3
dtype: int64

## All Ethnicites above

In [19]:
data['Age'].unique()

array(['25-34', '35-44', '18-24', 'Under 18', '55+', '45-54'],
      dtype=object)

In [20]:
pd.value_counts(data['Age'].values)

35-44       267
25-34       265
18-24       181
45-54       178
55+         158
Under 18      7
dtype: int64

## All Ages above

In [21]:
data['Brand'].unique()

array(['Apple', 'Google', 'Samsung', 'LG', 'Huawei', 'OnePlus',
       'ZTE / Nubia', 'Other Android (please specify brand)', 'Nokia',
       'Motorola'], dtype=object)

In [22]:
pd.value_counts(data['Brand'].values)

Apple                                   423
Samsung                                 420
LG                                       90
Motorola                                 33
Google                                   30
Other Android (please specify brand)     29
OnePlus                                   9
ZTE / Nubia                               9
Nokia                                     7
Huawei                                    6
dtype: int64

## Brand numbers above

In [23]:
data['Tier'].unique()

array(['Budget', 'Mid', 'Super Premium', 'Premium'], dtype=object)

In [24]:
pd.value_counts(data['Tier'].values)

Mid              399
Budget           358
Premium          170
Super Premium    129
dtype: int64

## Tiers numbers above

In [25]:
data['Loyalty'].unique()

array([nan, '1: Totally disagree', 6, 8, '9: Totally agree', 7, 2,
       '5: Neither disagree nor agree', 3, 4], dtype=object)

In [26]:
pd.value_counts(data['Loyalty'].values)

9: Totally agree                 322
8                                192
5: Neither disagree nor agree    162
7                                161
6                                 87
1: Totally disagree               40
3                                 34
4                                 32
2                                 22
dtype: int64

In [27]:
data[['Mobile Wallet / Pay Rate', 'Brand']]

      Mobile Wallet / Pay Rate    Brand
0                            1    Apple
1                            6   Google
2                            8  Samsung
3                            6   Google
4                            1   Google
...                        ...      ...
1051                         5  Samsung
1052                        10  Samsung
1053                         1  Samsung
1054                         7  Samsung
1055                        10  Samsung

[1056 rows x 2 columns]

In [28]:
data[data['Brand'] == "Samsung"]

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
2,False,2020-07-20 09:45:09,R_0faxTabFs6vw4xT,P03,Female,25-34,Samsung,NaN,NaN,NaN,Note 10+,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,True,2020-07-20 09:45:09,R_bl2zGnfrxGjh4Mt,P08,Female,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),Halo,...,NaN,Others (please specify),Cricket,Single with children,"Less than $15,000",Graduated high School,NaN,Homemaker or not working by choice,NaN,NaN,Social Savvies,1.0
20,True,2020-07-20 09:45:09,R_20kmaZ7fwmKJdLD,P21,Female,55+,Samsung,NaN,NaN,NaN,Note 8,NaN,...,NaN,T-Mobile,NaN,Life partner with children,"$150,000-$199,999",Masters / Post-graduate certification,NaN,Retired,"Farming, Forestry, and Fishing Occupations",NaN,Productives,1.0
32,True,2020-07-20 09:45:09,R_4YC0KZgfSkXSe9f,P33,Male,35-44,Samsung,NaN,NaN,NaN,S20,NaN,...,NaN,Verizon,NaN,Married with children,"$150,000-$199,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
33,True,2020-07-20 09:45:09,R_6WNhhRmRzrOaf4h,P34,Female,45-54,Samsung,NaN,NaN,NaN,Other model (please specify model),Samsung 7,...,NaN,Others (please specify),Consumer cellular,Married without children,"$35,000-$49,999",Graduated high School,NaN,Not employed,NaN,NaN,Productives,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,True,2020-07-20 09:45:17,R_26uJWCE8tWNTCBf,P1052,Male,25-34,Samsung,NaN,NaN,NaN,Other model (please specify model),s9+,...,NaN,Verizon,NaN,Single without children,"$35,000-$49,999",Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
1052,True,2020-07-20 09:45:17,R_9G3Ut4u09W4CWRD,P1053,Male,35-44,Samsung,NaN,NaN,NaN,A series (please specify model),galxger J3,...,NaN,Others (please specify),Straight talk,Single without children,"$25,000-$34,999",Graduated 4-year university,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Productives,1.0
1053,True,2020-07-20 09:45:17,R_6tiXdlFMoOUJprL,P1054,Male,45-54,Samsung,NaN,NaN,NaN,Other model (please specify model),Samsung Galaxy S9,...,NaN,AT&T,NaN,Married with children,"$75,000-$99,999",Graduated 4-year university,NaN,Employed full-time,"Machine Operators, Assemblers, and Inspectors",NaN,Productives,1.0
1054,True,2020-07-20 09:45:17,R_eUV7IyASFyS5EO1,P1055,Male,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),S9,...,NaN,Verizon,NaN,Single with children,"$150,000-$199,999","Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,1.0
1055,True,2020-07-20 09:45:17,R_5C2BmnIi0OOLJAx,P1056,Male,35-44,Samsung,NaN,NaN,NaN,S10 Plus,NaN,...,NaN,AT&T,NaN,Married with children,"$100,000-$149,999",Masters / Post-graduate certification,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Expressers,1.0

In [29]:
data[data['Brand'] == "Apple"]

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
0,True,2020-07-20 09:45:09,R_aXmDmwWggyyauot,P01,Male,25-34,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single without children,"$75,000-$99,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,NaN
5,True,2020-07-20 09:45:09,R_3EEkYkv5mbzboFL,P06,Female,25-34,Apple,NaN,Older Model (please enter model name),iPhone 6S,NaN,NaN,...,NaN,AT&T,NaN,Single without children,Prefer not to answer,Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Traditionalists,NaN
6,True,2020-07-20 09:45:09,R_6YdUBuksDEwG9CJ,P07,Female,18-24,Apple,NaN,iPhone 11 Pro Max,NaN,NaN,NaN,...,NaN,Verizon,NaN,Life partner without children,"$200,000 or more",Graduated 4-year university,NaN,Prefer not to answer,"Precision, Production, Craft, and Repair Occup...",NaN,Productives,1.0
10,True,2020-07-20 09:45:09,R_3DzTBGPU2XaSEhD,P11,Male,Under 18,Apple,NaN,iPhone 11 Pro Max,NaN,NaN,NaN,...,NaN,Sprint,NaN,Prefer not to answer,"Less than $15,000",Attended or currently attending 4-year university,NaN,Employed part-time,NaN,NaN,Productives,1.0
12,True,2020-07-20 09:45:09,R_1U0mnNepxn1XfQ9,P13,Male,35-44,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Sprint,NaN,Married with children,"$200,000 or more","Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Productives,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
971,True,2020-07-20 09:45:16,R_byMxDD69OIy44CN,P972,Male,45-54,Apple,NaN,iPhone 11 Pro,NaN,NaN,NaN,...,NaN,AT&T,NaN,Married with children,"$150,000-$199,999",Masters / Post-graduate certification,NaN,Employed full-time,Other (please specify),Analyst,Expressers,1.0
972,True,2020-07-20 09:45:16,R_082kycLpz1qAb4N,P973,Male,45-54,Apple,NaN,iPhone 8 Plus,NaN,NaN,NaN,...,NaN,AT&T,NaN,Married with children,"$50,000-$74,999",Graduated high School,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
975,True,2020-07-20 09:45:16,R_b8l6mpD0vUeH6Dz,P976,Male,45-54,Apple,NaN,iPhone 11 Pro Max,NaN,NaN,NaN,...,NaN,Others (please specify),Straight Talk,Single without children,"$35,000-$49,999",Graduated high School,NaN,Employed full-time,"Precision, Production, Craft, and Repair Occup...",NaN,Social Savvies,1.0
976,True,2020-07-20 09:45:16,R_esbbInOuP007XTL,P977,Male,45-54,Apple,NaN,iPhone XS,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single with children,"$50,000-$74,999",Graduated high School,NaN,Employed full-time,Transportation and Material Moving Occupations,NaN,Productives,1.0
977,True,2020-07-20 09:45:16,R_3yOxTRUY6tK7pRP,P978,Male,45-54,Apple,NaN,iPhone 11 Pro,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married with children,"$200,000 or more",Masters / Post-graduate certification,NaN,Employed full-time,Other (please specify),Construction,Social Savvies,1.0

In [30]:
#data.loc[data['Brand'] == "Samsung"]
data[data['Brand'] == 'Samsung']

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
2,False,2020-07-20 09:45:09,R_0faxTabFs6vw4xT,P03,Female,25-34,Samsung,NaN,NaN,NaN,Note 10+,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,True,2020-07-20 09:45:09,R_bl2zGnfrxGjh4Mt,P08,Female,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),Halo,...,NaN,Others (please specify),Cricket,Single with children,"Less than $15,000",Graduated high School,NaN,Homemaker or not working by choice,NaN,NaN,Social Savvies,1.0
20,True,2020-07-20 09:45:09,R_20kmaZ7fwmKJdLD,P21,Female,55+,Samsung,NaN,NaN,NaN,Note 8,NaN,...,NaN,T-Mobile,NaN,Life partner with children,"$150,000-$199,999",Masters / Post-graduate certification,NaN,Retired,"Farming, Forestry, and Fishing Occupations",NaN,Productives,1.0
32,True,2020-07-20 09:45:09,R_4YC0KZgfSkXSe9f,P33,Male,35-44,Samsung,NaN,NaN,NaN,S20,NaN,...,NaN,Verizon,NaN,Married with children,"$150,000-$199,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
33,True,2020-07-20 09:45:09,R_6WNhhRmRzrOaf4h,P34,Female,45-54,Samsung,NaN,NaN,NaN,Other model (please specify model),Samsung 7,...,NaN,Others (please specify),Consumer cellular,Married without children,"$35,000-$49,999",Graduated high School,NaN,Not employed,NaN,NaN,Productives,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1051,True,2020-07-20 09:45:17,R_26uJWCE8tWNTCBf,P1052,Male,25-34,Samsung,NaN,NaN,NaN,Other model (please specify model),s9+,...,NaN,Verizon,NaN,Single without children,"$35,000-$49,999",Graduated 4-year university,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,1.0
1052,True,2020-07-20 09:45:17,R_9G3Ut4u09W4CWRD,P1053,Male,35-44,Samsung,NaN,NaN,NaN,A series (please specify model),galxger J3,...,NaN,Others (please specify),Straight talk,Single without children,"$25,000-$34,999",Graduated 4-year university,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Productives,1.0
1053,True,2020-07-20 09:45:17,R_6tiXdlFMoOUJprL,P1054,Male,45-54,Samsung,NaN,NaN,NaN,Other model (please specify model),Samsung Galaxy S9,...,NaN,AT&T,NaN,Married with children,"$75,000-$99,999",Graduated 4-year university,NaN,Employed full-time,"Machine Operators, Assemblers, and Inspectors",NaN,Productives,1.0
1054,True,2020-07-20 09:45:17,R_eUV7IyASFyS5EO1,P1055,Male,35-44,Samsung,NaN,NaN,NaN,Other model (please specify model),S9,...,NaN,Verizon,NaN,Single with children,"$150,000-$199,999","Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,1.0
1055,True,2020-07-20 09:45:17,R_5C2BmnIi0OOLJAx,P1056,Male,35-44,Samsung,NaN,NaN,NaN,S10 Plus,NaN,...,NaN,AT&T,NaN,Married with children,"$100,000-$149,999",Masters / Post-graduate certification,NaN,Employed full-time,"Executive, Administrative, and Managerial Occu...",NaN,Expressers,1.0

In [31]:
data['Brand'].unique()

array(['Apple', 'Google', 'Samsung', 'LG', 'Huawei', 'OnePlus',
       'ZTE / Nubia', 'Other Android (please specify brand)', 'Nokia',
       'Motorola'], dtype=object)

In [32]:
three_cat = data

three_cat['Brand'] = three_cat['Brand'].replace(['Google', 'LG', 'Huawei', 'OnePlus',
       'ZTE / Nubia', 'Other Android (please specify brand)', 'Nokia',
       'Motorola'], 'Other')

three_cat.head()

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
0,True,2020-07-20 09:45:09,R_aXmDmwWggyyauot,P01,Male,25-34,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single without children,"$75,000-$99,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,NaN
1,True,2020-07-20 09:45:09,R_2n4mDypHvVcry9T,P02,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Masters / Post-graduate certification,NaN,Employed full-time,"Handlers, Equipment Cleaners, Helpers, and Lab...",NaN,Expressers,NaN
2,False,2020-07-20 09:45:09,R_0faxTabFs6vw4xT,P03,Female,25-34,Samsung,NaN,NaN,NaN,Note 10+,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,True,2020-07-20 09:45:09,R_2shSLWBLzfglhJj,P04,Female,25-34,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,AT&T,NaN,Life partner without children,Prefer not to answer,"Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,NaN
4,True,2020-07-20 09:45:09,R_41scVuzu1NVb66h,P05,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Prefer not to answer,NaN,Prefer not to answer,NaN,NaN,Expressers,NaN

In [33]:
sam = three_cat[data['Brand'] == 'Samsung']
apple = three_cat[data['Brand'] == 'Apple']

other = three_cat.loc[~data['Brand'].isin(['Samsung', 'Apple'])] 

other.head()

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
1,True,2020-07-20 09:45:09,R_2n4mDypHvVcry9T,P02,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Masters / Post-graduate certification,NaN,Employed full-time,"Handlers, Equipment Cleaners, Helpers, and Lab...",NaN,Expressers,NaN
3,True,2020-07-20 09:45:09,R_2shSLWBLzfglhJj,P04,Female,25-34,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,AT&T,NaN,Life partner without children,Prefer not to answer,"Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,NaN
4,True,2020-07-20 09:45:09,R_41scVuzu1NVb66h,P05,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Prefer not to answer,NaN,Prefer not to answer,NaN,NaN,Expressers,NaN
8,True,2020-07-20 09:45:09,R_8Jj9vcoo6IiDqaV,P09,Male,25-34,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,Others (please specify),NaN,Single without children,"Less than $15,000",Graduated 2-year college or technical school,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,1.0
9,True,2020-07-20 09:45:09,R_eVuYroFNWeCScEB,P10,Female,18-24,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Life partner without children,"$200,000 or more",Graduated 4-year university,NaN,Retired,"Executive, Administrative, and Managerial Occu...",NaN,Productives,1.0

In [34]:
sam_rate = sam
apple_rate = apple
other_rate = other

for name in sam_rate.columns:
    if " rate" not in name:
        sam_rate = sam_rate.drop(name,axis=1)
        apple_rate = apple_rate.drop(name,axis=1)
        other_rate = other_rate.drop(name,axis=1)

In [35]:
sam_rate.loc[:, 'Default  phone app rate':'Other Earbuds Brand rate'].mean()

Default  phone app rate            4.122951
Other voice call rate              3.870000
Face Time rate                          NaN
Default video call app rate        4.000000
Google Duo rate                    3.980100
                                     ...
Apple Airpod or Airpod Pro rate    4.315789
Samsung Galaxy Buds rate           4.407080
Amazon Echo Buds rate              4.033333
Google Pixel Buds rate             3.979592
Other Earbuds Brand rate           4.310345
Length: 204, dtype: float64

In [36]:
apple_rate.loc[:, 'Default  phone app rate':'Other Earbuds Brand rate'].mean()

Default  phone app rate            4.171662
Other voice call rate              3.989796
Face Time rate                     4.158038
Default video call app rate             NaN
Google Duo rate                    3.732824
                                     ...
Apple Airpod or Airpod Pro rate    4.525000
Samsung Galaxy Buds rate           4.326531
Amazon Echo Buds rate              4.142857
Google Pixel Buds rate             4.069767
Other Earbuds Brand rate           4.059701
Length: 204, dtype: float64

In [37]:
other_rate.loc[:, 'Default  phone app rate':'Other Earbuds Brand rate'].mean()

Default  phone app rate            3.902174
Other voice call rate              3.510638
Face Time rate                          NaN
Default video call app rate        3.933333
Google Duo rate                    3.904110
                                     ...
Apple Airpod or Airpod Pro rate    4.125000
Samsung Galaxy Buds rate           4.050000
Amazon Echo Buds rate              4.000000
Google Pixel Buds rate             3.666667
Other Earbuds Brand rate           3.658537
Length: 204, dtype: float64

In [38]:
phone_app = ['Default  phone app rate', 'Other voice call rate']
phone_app_graph = data.groupby('Brand')[phone_app].mean()
print(phone_app_graph)

         Default  phone app rate  Other voice call rate
Brand
Apple                   4.171662               3.989796
Other                   3.902174               3.510638
Samsung                 4.122951               3.870000

In [39]:
sat_group = three_cat.groupby('Brand')['Current Staisfaction'].mean()
print(sat_group)

Brand
Apple      86.855792
Other      80.159624
Samsung    85.721429
Name: Current Staisfaction, dtype: float64

In [40]:
satis = three_cat['Current Staisfaction'] 
a = three_cat.corr().unstack().sort_values().drop_duplicates()

# Form Factor

In [41]:
three_cat.head()

,Finished,Date,Response ID,PID,Gender,Age,Brand,Other Android,iPhone Model,Older iPhone Model,Samsung Model,Other Samsung Model,...,Other Ethnicity,Wireless Carrier,Other Wireless Carrier,Marital Status,Household Income,Education,Other Education,Employment,Occupation,Other Occupation,Segment,gc
0,True,2020-07-20 09:45:09,R_aXmDmwWggyyauot,P01,Male,25-34,Apple,NaN,iPhone 11,NaN,NaN,NaN,...,NaN,Verizon,NaN,Single without children,"$75,000-$99,999",Masters / Post-graduate certification,NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Expressers,NaN
1,True,2020-07-20 09:45:09,R_2n4mDypHvVcry9T,P02,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Masters / Post-graduate certification,NaN,Employed full-time,"Handlers, Equipment Cleaners, Helpers, and Lab...",NaN,Expressers,NaN
2,False,2020-07-20 09:45:09,R_0faxTabFs6vw4xT,P03,Female,25-34,Samsung,NaN,NaN,NaN,Note 10+,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,True,2020-07-20 09:45:09,R_2shSLWBLzfglhJj,P04,Female,25-34,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,AT&T,NaN,Life partner without children,Prefer not to answer,"Ph.D. or professional degrees (M.D., J.D.)",NaN,Employed full-time,"Professional, Technical, and Related Occupations",NaN,Productives,NaN
4,True,2020-07-20 09:45:09,R_41scVuzu1NVb66h,P05,Male,35-44,Other,NaN,NaN,NaN,NaN,NaN,...,NaN,T-Mobile,NaN,Married without children,Prefer not to answer,Prefer not to answer,NaN,Prefer not to answer,NaN,NaN,Expressers,NaN

In [42]:
tcf = three_cat

for cols in three_cat:
    if (("Slate" in cols) | ("Book" in cols) | ('Brand' in cols)):
        print(three_cat.columns.get_loc(cols))

6
16
17
18
19
20
22
23
24
25
26
27
28
29
31
32
33
34
35
1102
1138
1141
1142
1179
1180
1215
1216
1247

## Proportion of Samsung Respondents Choosing Form Factor as 1st

In [146]:
import numpy as np


df_form_sam = sam.iloc[:, np.r_[6:7, 25:34]]

# 1st place proportion
for cols in df_form_sam:
    print(cols, len(df_form_sam[df_form_sam[cols] == 1.0])/420)

Brand 0.0
Top Slate + Accessory 0.1523809523809524
Top Slate Large Display 0.24761904761904763
Top Slate Medium Display 0.23809523809523808
Top Slate Small Display 0.030952380952380953
Top Book Inner Panels 0.06666666666666667
Top Wallet Format 0.10714285714285714
Top Book Outer Panels 0.06666666666666667
Top Book 3 Panels 0.02857142857142857
Top Book Sliding Display 0.05952380952380952

## Proportion of Samsung Respondents Choosing Form Factor as 2nd

In [147]:
# 2nd place proportion 
for cols in df_form_sam:
    print(cols, len(df_form_sam[df_form_sam[cols] == 2.0])/420)

Brand 0.0
Top Slate + Accessory 0.14761904761904762
Top Slate Large Display 0.16428571428571428
Top Slate Medium Display 0.15
Top Slate Small Display 0.05476190476190476
Top Book Inner Panels 0.14285714285714285
Top Wallet Format 0.06190476190476191
Top Book Outer Panels 0.11666666666666667
Top Book 3 Panels 0.05714285714285714
Top Book Sliding Display 0.10238095238095238

## Proportion of Apple Respondents Choosing Form Factor as 1st

In [148]:
df_form_apple = apple.iloc[:, np.r_[6:7, 25:34]]

# 1st place proportion
for cols in df_form_apple:
    print(cols, len(df_form_apple[df_form_apple[cols] == 1.0])/423)

Brand 0.0
Top Slate + Accessory 0.17257683215130024
Top Slate Large Display 0.22458628841607564
Top Slate Medium Display 0.23877068557919623
Top Slate Small Display 0.0591016548463357
Top Book Inner Panels 0.05673758865248227
Top Wallet Format 0.0851063829787234
Top Book Outer Panels 0.061465721040189124
Top Book 3 Panels 0.04728132387706856
Top Book Sliding Display 0.04964539007092199

## Proportion of Apple Respondents Choosing Form Factor as 2nd

In [156]:
# 2nd place proportion
for cols in df_form_apple:
    print(cols, len(df_form_apple[df_form_apple[cols] == 2.0])/423)

Brand 0.0
Top Slate + Accessory 0.14420803782505912
Top Slate Large Display 0.2033096926713948
Top Slate Medium Display 0.14420803782505912
Top Slate Small Display 0.0425531914893617
Top Book Inner Panels 0.13238770685579196
Top Wallet Format 0.09219858156028368
Top Book Outer Panels 0.08037825059101655
Top Book 3 Panels 0.037825059101654845
Top Book Sliding Display 0.1182033096926714

## Proportion of Other Respondents Choosing Form Factor as 1st

In [158]:
df_form_other = other.iloc[:, np.r_[6:7, 25:34]]

# 1st place proportion
for cols in df_form_other:
    print(cols, len(df_form_other[df_form_other[cols] == 1.0])/213)

Brand 0.0
Top Slate + Accessory 0.12206572769953052
Top Slate Large Display 0.2347417840375587
Top Slate Medium Display 0.28169014084507044
Top Slate Small Display 0.06572769953051644
Top Book Inner Panels 0.07511737089201878
Top Wallet Format 0.051643192488262914
Top Book Outer Panels 0.03286384976525822
Top Book 3 Panels 0.046948356807511735
Top Book Sliding Display 0.07511737089201878

## Proportion of Other Respondents Choosing Form Factor as 2nd

In [155]:
df_form_other = other.iloc[:, np.r_[6:7, 25:34]]

# 2nd place proportion
for cols in df_form_other:
    print(cols, len(df_form_other[df_form_other[cols] == 2.0])/213)

Brand 0.0
Top Slate + Accessory 0.13145539906103287
Top Slate Large Display 0.13615023474178403
Top Slate Medium Display 0.11267605633802817
Top Slate Small Display 0.046948356807511735
Top Book Inner Panels 0.1267605633802817
Top Wallet Format 0.09859154929577464
Top Book Outer Panels 0.15492957746478872
Top Book 3 Panels 0.056338028169014086
Top Book Sliding Display 0.12206572769953052

# Form Factor Based on Types of Users

In [56]:
browsers = pd.read_csv('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Browsers - Phase 1 Elements of Value - DRAFT.csv')
expressers = pd.read_csv('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Expressers - Phase 1 Elements of Value - DRAFT.csv')
productives = pd.read_csv('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Productives - Phase 1 Elements of Value - DRAFT.csv')
ss = pd.read_csv('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Social Savvies - Phase 1 Elements of Value - DRAFT.csv')
traditionalists = pd.read_csv('/Volumes/bresslergroup/Shared/BG Clients/94204 - Samsung EOV/05 - UR/4 - Data/20200720a - Traditionalists - Phase 1 Elements of Value - DRAFT.csv')

## First place

## Browsers

In [10]:
browsers.head()

,Date,Response ID,PID,Segment,Gender,Age,Likelihood to Buy Devices from Non-Preferred Brand,Ethnicity,Other Ethnicity,Wireless Carrier,...,Earbuds Therapeutic,Earbuds Fun,Earbuds Attractiveness,Earbuds Access,Earbuds Transcendence,Earbuds Hope,Earbuds Actualization,Earbuds Motivates,Earbuds Heirloom,Earbuds Belonging
0,44032.40635,R_emmWiQX8ua9Oke1,P59,Browsers,Male,55+,5.0,White / Caucasian,NaN,AT&T,...,0,0,0,1,0,0,0,0,0,0
1,44032.40635,R_9NR1BFYKwkUoyhf,P64,Browsers,Female,55+,4.0,White / Caucasian,NaN,Verizon,...,0,0,0,0,0,0,0,0,0,0
2,44032.40635,R_eXVTTbGsVMRbXV3,P82,Browsers,Male,55+,7.0,White / Caucasian,NaN,Others (please specify),...,0,0,0,0,0,0,0,0,0,0
3,44032.40635,R_6SGy4yufj66lOoB,P94,Browsers,Female,55+,5.0,White / Caucasian,NaN,AT&T,...,0,0,0,0,0,0,0,0,0,0
4,44032.40635,R_25iXa7xmLk7RuyV,P96,Browsers,Male,55+,8.0,White / Caucasian,NaN,Others (please specify),...,0,0,0,0,0,0,0,0,0,0

In [11]:
browsers.columns.tolist()

['Date',
 'Response ID',
 'PID',
 'Segment',
 'Gender',
 'Age',
 'Likelihood to Buy Devices from Non-Preferred Brand',
 'Ethnicity',
 'Other Ethnicity',
 'Wireless Carrier',
 'Other Wireless Carrier',
 'Marital Status',
 'Household Income',
 'Education',
 'Other Education',
 'Employment',
 'Occupation',
 'Other Occupation',
 'Brand',
 'Other Android',
 'iPhone Model',
 'Older iPhone Model',
 'Samsung Model',
 'Other Samsung Model',
 'Google Model',
 'Other Google Model',
 'Other Android Model',
 'List Price',
 'Preferred Brand',
 'Other Preferred Brand',
 'Loyalty',
 'Loyalty Proud',
 'Loyalty Promoter',
 'Loyalty Recommend',
 'Next Cost',
 'Tier',
 'Latest premium (over $600)',
 'Latest ultra-premium (over $1,200)',
 'Lite or Essential premium smartphones',
 'Latest mid-tier  ($300 and $600)',
 'Latest budget or value  (under $300)',
 'Earlier generation premium',
 'Earlier generation mid-tier',
 'Earlier generation budget',
 'Used',
 'Cheap',
 'Good Deal',
 'Getting Expensive',
 'Too Expensive',
 'Buy Deal',
 'Buy Getting Expensive',
 'Voice or Video calls, Messaging, Email',
 'Taking Pictures or Videos',
 'Streaming Video',
 'Streaming Music',
 'Playing Games',
 'Productivity tools',
 'Health/Fitness',
 'Smart Home Control',
 'Internet Browsing',
 'Shopping / Coupon Apps',
 'Mobile Wallet / Pay',
 'Voice Assistant',
 'Navigation & Maps',
 'Device Tracking',
 'Family / Personal Security',
 'Social Media',
 'Third-party & Carrier Preloads',
 'Connectivity with PC/Laptop, Tablet',
 'Usage with Earbuds/Headphones',
 'Usage with Smart Watches, Fitness Bands',
 'Augmented Reality / Virtual Reality',
 'Cloud storage',
 'Personalizing phone content',
 'Slate + Accessory',
 'Slate Large Display',
 'Slate Medium Display',
 'Slate Small Display',
 'Book Inner Panels',
 'Wallet Format',
 'Book Outer Panels',
 'Book 3 Panels',
 'Book Sliding Display',
 'Top Slate + Accessory',
 'Top Slate Large Display',
 'Top Slate Medium Display',
 'Top Slate Small Display',
 'Top Book Inner Panels',
 'Top Wallet Format',
 'Top Book Outer Panels',
 'Top Book 3 Panels',
 'Top Book Sliding Display',
 'Current Satisfaction',
 'Satisfied',
 'Ideal Saves Time',
 'Ideal Simplifies',
 'Ideal Makes Money',
 'Ideal Reduce Risk',
 'Ideal Organizes',
 'Ideal Integrates',
 'Ideal Connects',
 'Ideal Reduce Effort',
 'Ideal Avoid Hassles',
 'Ideal Reduce Cost',
 'Ideal Quality',
 'Ideal Variety',
 'Ideal Senses',
 'Ideal Informs',
 'Ideal Reduce Anxiety',
 'Ideal Rewards',
 'Ideal Nostalgia',
 'Ideal Aesthetics',
 'Ideal Badge Value',
 'Ideal Wellness',
 'Ideal Therapeutic',
 'Ideal Fun',
 'Ideal Attractiveness',
 'Ideal Access',
 'Ideal Transcendence',
 'Ideal Hope',
 'Ideal Actualization',
 'Ideal Motivates',
 'Ideal Heirloom',
 'Ideal Belonging',
 'Current Saves Time Rate',
 'Current Simplifies Rate',
 'Current Makes Money Rate',
 'Current Reduce Risk Rate',
 'Current Organizes Rate',
 'Current Integrates  Rate',
 'Current Connects Rate',
 'Current Reduce Effort Rate',
 'Current Avoid Hassles Rate',
 'Current Reduce Cost Rate',
 'Current Quality Rate',
 'Current Variety Rate',
 'Current Senses Rate',
 'Current Informs Rate',
 'Current Reduce Anxiety Rate',
 'Current Rewards Rate',
 'Current Nostalgia Rate',
 'Current Aesthetics Rate',
 'Current Badge Value Rate',
 'Current Wellness Rate',
 'Current Therapeutic Rate',
 'Current Fun Rate',
 'Current Attractiveness Rate',
 'Current Access Rate',
 'Current Transcendence Rate',
 'Current Hope Rate',
 'Current Actualization Rate',
 'Current Motivates Rate',
 'Current Heirloom Rate',
 'Current Belonging Rate',
 'Voice or Video calls, Messaging, Email Rate ',
 'Taking Pictures or Videos Rate',
 'Streaming Video Rate',
 'Streaming Music Rate',
 'Playing Games Rate',
 'Productivity tools Rate',
 'Health/Fitness Rate',
 'Smart Home Control Rate',
 'Internet Browsing Rate',
 'Shopping / Coupon Apps Rate',
 'Mobile Wallet / Pay Rate',
 'Voice Assistant Rate',
 'Navigation & Maps Rate',
 'Device Tracking Rate',
 'Family / Personal Security Rate',
 'Social Media Rate',
 'Third-party & Carrier Preloads Rate',
 'Connectivity with PC/Laptop, Tablet Rate',
 'Usage with Earbuds/Headphones Rate',
 'Usage with Smart Watches, Fitness Bands Rate',
 'Augmented Reality / Virtual Reality Rate',
 'Cloud storage Rate',
 'Personalizing phone content Rate',
 'Current Size',
 'Current Shape',
 'Current Buttons',
 'Current Chassis Material',
 'Current Color Choices',
 'Current Look and Feel',
 'Current Aspect Ratio',
 'Current Display Color',
 'Current Refresh Rate',
 'Current Camera',
 'Current Battery Capacity',
 'Current Waterproof / Dust proof',
 'Current Wireless Charging',
 'Current Fast Charging',
 'Current Touch and Screen Responsiveness',
 'Current Storage Capacity',
 'Current General User Interface',
 'Current Support for one-hand use',
 'Current Consistent usability',
 'Current Pakcaging',
 'Default  phone app rate',
 'Other voice call rate',
 'Other voice app',
 'Voice Call Saves Time',
 'Voice Call Simplifies',
 'Voice Call Makes Money',
 'Voice Call Reduce Risk',
 'Voice Call Organizes',
 'Voice Call Integrates',
 'Voice Call Connects',
 'Voice Call Reduce Effort',
 'Voice Call Avoid Hassles',
 'Voice Call Reduce Cost',
 'Voice Call Quality',
 'Voice Call Variety',
 'Voice Call Senses',
 'Voice Call Informs',
 'Voice Call Reduce Anxiety',
 'Voice Call Rewards',
 'Voice Call Nostalgia',
 'Voice Call Aesthetics',
 'Voice Call Badge Value',
 'Voice Call Wellness',
 'Voice Call Therapeutic',
 'Voice Call Fun',
 'Voice Call Attractiveness',
 'Voice Call Access',
 'Voice Call Transcendence',
 'Voice Call Hope',
 'Voice Call Actualization',
 'Voice Call Motivates',
 'Voice Call Heirloom',
 'Voice Call Belonging',
 'Face Time rate',
 'Default video call app rate',
 'Google Duo rate',
 'Skype rate',
 'Facebook Messenger video rate',
 'Whatsapp video rate',
 'Zoom rate',
 'Other video app rate',
 'Other video apps',
 'Video Call Saves Time',
 'Video Call Simplifies',
 'Video Call Makes Money',
 'Video Call Reduce Risk',
 'Video Call Organizes',
 'Video Call Integrates',
 'Video Call Connects',
 'Video Call Reduce Effort',
 'Video Call Avoid Hassles',
 'Video Call Reduce Cost',
 'Video Call Quality',
 'Video Call Variety',
 'Video Call Senses',
 'Video Call Informs',
 'Video Call Reduce Anxiety',
 'Video Call Rewards',
 'Video Call Nostalgia',
 'Video Call Aesthetics',
 'Video Call Badge Value',
 'Video Call Wellness',
 'Video Call Therapeutic',
 'Video Call Fun',
 'Video Call Attractiveness',
 'Video Call Access',
 'Video Call Transcendence',
 'Video Call Hope',
 'Video Call Actualization',
 'Video Call Motivates',
 'Video Call Heirloom',
 'Video Call Belonging',
 'Multi-Person Video Call',
 'iMessage rate',
 'Default messaging app rate',
 'Facebook Messenger rate',
 'Whatsapp rate',
 'Snapchat rate',
 'Other messaging rate',
 'Other Messaging Apps',
 'Messaging Saves Time',
 'Messaging Simplifies',
 'Messaging Makes Money',
 'Messaging Reduce Risk',
 'Messaging Organizes',
 'Messaging Integrates',
 'Messaging Connects',
 'Messaging Reduce Effort',
 'Messaging Avoid Hassles',
 'Messaging Reduce Cost',
 'Messaging Quality',
 'Messaging Variety',
 'Messaging Senses',
 'Messaging Informs',
 'Messaging Reduce Anxiety',
 'Messaging Rewards',
 'Messaging Nostalgia',
 'Messaging Aesthetics',
 'Messaging Badge Value',
 'Messaging Wellness',
 'Messaging Therapeutic',
 'Messaging Fun',
 'Messaging Attractiveness',
 'Messaging Access',
 'Messaging Transcendence',
 'Messaging Hope',
 'Messaging Actualization',
 'Messaging Motivates',
 'Messaging Heirloom',
 'Messaging Belonging',
 'RCS',
 'Default Apple Mail rate',
 'Default Email rate',
 'Gmail rate',
 'Microsoft Outlook or Hotmail rate',
 'Yahoo Mail rate',
 'Other email rate',
 'Other Email Apps',
 'Email Saves Time',
 'Email Simplifies',
 'Email Makes Money',
 'Email Reduce Risk',
 'Email Organizes',
 'Email Integrates',
 'Email Connects',
 'Email Reduce Effort',
 'Email Avoid Hassles',
 'Email Reduce Cost',
 'Email Quality',
 'Email Variety',
 'Email Senses',
 'Email Informs',
 'Email Reduce Anxiety',
 'Email Rewards',
 'Email Nostalgia',
 'Email Aesthetics',
 'Email Badge Value',
 'Email Wellness',
 'Email Therapeutic',
 'Email Fun',
 'Email Attractiveness',
 'Email Access',
 'Email Transcendence',
 'Email Hope',
 'Email Actualization',
 'Email Motivates',
 'Email Heirloom',
 'Email Belonging',
 'Safari rate',
 'Samsung Internet rate',
 'Chrome rate',
 'Edge rate',
 'Firefox rate',
 'Other internet rate',
 'Other Internet Apps',
 'Internet Saves Time',
 'Internet Simplifies',
 'Internet Makes Money',
 'Internet Reduce Risk',
 'Internet Organizes',
 'Internet Integrates',
 'Internet Connects',
 'Internet Reduce Effort',
 'Internet Avoid Hassles',
 'Internet Reduce Cost',
 'Internet Quality',
 'Internet Variety',
 'Internet Senses',
 'Internet Informs',
 'Internet Reduce Anxiety',
 'Internet Rewards',
 'Internet Nostalgia',
 'Internet Aesthetics',
 'Internet Badge Value',
 'Internet Wellness',
 'Internet Therapeutic',
 'Internet Fun',
 'Internet Attractiveness',
 'Internet Access',
 'Internet Transcendence',
 'Internet Hope',
 'Internet Actualization',
 'Internet Motivates',
 'Internet Heirloom',
 'Internet Belonging',
 'Facebook rate',
 'Instagram rate',
 'Pinterest rate',
 'SnapChat social rate',
 'LinkedIn rate',
 'Twitter rate',
 'Discord rate',
 'Reddit rate',
 'Yelp rate',
 'Whatspp rate',
 'Tumblr rate',
 'TikTok rate',
 'Other Social Media rate',
 'Other Social Media Apps',
 'Social Saves Time',
 'Social Simplifies',
 'Social Makes Money',
 'Social Reduce Risk',
 'Social Organizes',
 'Social Integrates',
 'Social Connects',
 'Social Reduce Effort',
 'Social Avoid Hassles',
 'Social Reduce Cost',
 'Social Quality',
 'Social Variety',
 'Social Senses',
 'Social Informs',
 'Social Reduce Anxiety',
 'Social Rewards',
 'Social Nostalgia',
 'Social Aesthetics',
 'Social Badge Value',
 'Social Wellness',
 'Social Therapeutic',
 'Social Fun',
 'Social Attractiveness',
 'Social Access',
 'Social Transcendence',
 'Social Hope',
 'Social Actualization',
 'Social Motivates',
 'Social Heirloom',
 'Social Belonging',
 'Rear camera (standard) rate',
 'Rear camera (wide-angle or ultra wide angle) rate',
 'Rear camera (telephoto) rate',
 'Selfie camera (standard) rate',
 'Selfie camera (wide angle or group) rate',
 'Portrait, Live Focus or Bokeh (blurring of background) rate',
 'Night Mode Performance rate',
 'Zoom (Optical, Hybrid and Digital) rate',
 'Macro (closeup) rate',
 'Filters, Special Effects (e.g., Fun AR stickers, Panorama..) rate',
 'Multiple cameras at the same time rate',
 'Other camera feature rate',
 'Other Camera Features',
 'Camera Saves Time',
 'Camera Simplifies',
 'Camera Makes Money',
 'Camera Reduce Risk',
 'Camera Organizes',
 'Camera Integrates',
 'Camera Connects',
 'Camera Reduce Effort',
 'Camera Avoid Hassles',
 'Camera Reduce Cost',
 'Camera Quality',
 'Camera Variety',
 'Camera Senses',
 'Camera Informs',
 'Camera Reduce Anxiety',
 'Camera Rewards',
 'Camera Nostalgia',
 'Camera Aesthetics',
 'Camera Badge Value',
 'Camera Wellness',
 'Camera Therapeutic',
 'Camera Fun',
 'Camera Attractiveness',
 'Camera Access',
 'Camera Transcendence',
 'Camera Hope',
 'Camera Actualization',
 'Camera Motivates',
 'Camera Heirloom',
 'Camera Belonging',
 'Video Portrait, Live Focus or Bokeh rate',
 'Slow motion rate',
 'Time Lapse / HyperLapse rate',
 'Video Night Mode Performance rate',
 'Multiple Cameras Video rate',
 'Video: HD rate',
 'Video: 4K rate',
 'Attention 1',
 'Optical or DIgital Stabilization rate',
 'Video Special Effects rate',
 'Other Video Camera Features rate',
 'Other video camera features',
 'Camcorder Saves Time',
 'Camcorder Simplifies',
 'Camcorder Makes Money',
 'Camcorder Reduce Risk',
 'Camcorder Organizes',
 'Camcorder Integrates',
 'Camcorder Connects',
 'Camcorder Reduce Effort',
 'Camcorder Avoid Hassles',
 'Camcorder Reduce Cost',
 'Camcorder Quality',
 'Camcorder Variety',
 'Camcorder Senses',
 'Camcorder Informs',
 'Camcorder Reduce Anxiety',
 'Camcorder Rewards',
 'Camcorder Nostalgia',
 'Camcorder Aesthetics',
 'Camcorder Badge Value',
 'Camcorder Wellness',
 'Camcorder Therapeutic',
 'Camcorder Fun',
 'Camcorder Attractiveness',
 'Camcorder Access',
 'Camcorder Transcendence',
 'Camcorder Hope',
 'Camcorder Actualization',
 'Camcorder Motivates',
 'Camcorder Heirloom',
 'Camcorder Belonging',
 'Photos (Apple) rate',
 'Gallery (Samsung) rate',
 'Google Photos rate',
 'Lightroom rate',
 'Adobe Photoshop Express rate',
 'Snapseed rate',
 'VSCO rate',
 'Other photo storage rate',
 'Other photo storage apps',
 'Photo Storage Saves Time',
 'Photo Storage Simplifies',
 'Photo Storage Makes Money',
 'Photo Storage Reduce Risk',
 'Photo Storage Organizes',
 'Photo Storage Integrates',
 'Photo Storage Connects',
 'Photo Storage Reduce Effort',
 'Photo Storage Avoid Hassles',
 'Photo Storage Reduce Cost',
 'Photo Storage Quality',
 'Photo Storage Variety',
 'Photo Storage Senses',
 'Photo Storage Informs',
 'Photo Storage Reduce Anxiety',
 'Photo Storage Rewards',
 'Photo Storage Nostalgia',
 'Photo Storage Aesthetics',
 'Photo Storage Badge Value',
 'Photo Storage Wellness',
 'Photo Storage Therapeutic',
 'Photo Storage Fun',
 'Photo Storage Attractiveness',
 'Photo Storage Access',
 'Photo Storage Transcendence',
 'Photo Storage Hope',
 'Photo Storage Actualization',
 'Photo Storage Motivates',
 'Photo Storage Heirloom',
 'Photo Storage Belonging',
 'Photo Transfer Method',
 'Apple Arcade rate',
 'Google Play Game Subscription rate',
 'Google Stadia Cloud Gaming Subscription rate',
 'Nvidia Cloud Gaming Subscription rate',
 'Microsoft Xbox Subscription rate',
 'Sony Playstation Online Subscription rate',
 'Play Preloaded games Only rate',
 'Play Preloaded games and downloaded games, no subscription rate',
 'Other Gaming App rate',
 'Other Gaming Apps',
 'Gaming Saves Time',
 'Gaming Simplifies',
 'Gaming Makes Money',
 'Gaming Reduce Risk',
 'Gaming Organizes',
 'Gaming Integrates',
 'Gaming Connects',
 'Gaming Reduce Effort',
 'Gaming Avoid Hassles',
 'Gaming Reduce Cost',
 'Gaming Quality',
 'Gaming Variety',
 'Gaming Senses',
 'Gaming Informs',
 'Gaming Reduce Anxiety',
 'Gaming Rewards',
 'Gaming Nostalgia',
 'Gaming Aesthetics',
 'Gaming Badge Value',
 'Gaming Wellness',
 'Gaming Therapeutic',
 'Gaming Fun',
 'Gaming Attractiveness',
 'Gaming Access',
 'Gaming Transcendence',
 'Gaming Hope',
 'Gaming Actualization',
 'Gaming Motivates',
 'Gaming Heirloom',
 'Gaming Belonging',
 'Apple Music Paid',
 'YouTube Music Paid',
 'Spotify Paid',
 'Pandora Paid',
 'iHeartRadio Paid',
 'Tidal Paid',
 'Amazon Music Paid',
 'Google Play Music Paid',
 'Other Music Subscription Paid',
 'Other Music Subscription Apps',
 'Apple Music rate',
 'YouTube Music rate',
 'Spotify rate',
 'Pandora rate',
 'iHeartRadio rate',
 'Tidal rate',
 'Amazon Music rate',
 'Google Play Music rate',
 'Other Music Subscription rate',
 'Other Music Subscription Apps 2',
 'Music Saves Time',
 'Music Simplifies',
 'Music Makes Money',
 'Music Reduce Risk',
 'Music Organizes',
 'Music Integrates',
 'Music Connects',
 'Music Reduce Effort',
 'Music Avoid Hassles',
 'Music Reduce Cost',
 'Music Quality',
 'Music Variety',
 'Music Senses',
 'Music Informs',
 'Music Reduce Anxiety',
 'Music Rewards',
 'Gaming Nostalgia2',
 'Music Aesthetics',
 'Music Badge Value',
 'Music Wellness',
 'Music Therapeutic',
 'Music Fun',
 'Music Attractiveness',
 'Music Access',
 'Music Transcendence',
 'Music Hope',
 'Music Actualization',
 'Music Motivates',
 'Music Heirloom',
 'Music Belonging',
 'Apple TV+ Paid',
 'Amazon Prime Video Paid',
 'Disney+ Paid',
 'Netflix Paid',
 'Hulu Paid',
 'CBS All Access Paid',
 'HBO Now or HBO MAX Paid',
 'NBC Peacock Service Paid',
 'YouTube TV Premium Paid',
 'Sling TV Paid',
 'Fubo TV Paid',
 'Philo Paid',
 'Quibi Paid',
 'Other Video Streaming Paid',
 'Other Video Streaming Apps',
 'Apple TV+ rate',
 'Amazon Prime Video rate',
 'Disney+ rate',
 'Netflix rate',
 'Hulu rate',
 'CBS All Access rate',
 'HBO Now or HBO MAX rate',
 'NBC Peacock Service rate',
 'YouTube TV Premium rate',
 'Sling TV rate',
 'Fubo TV rate',
 'Philo rate',
 'Quibi rate',
 'Other Video Streaming rate',
 'Other Video Streaming Apps 2',
 'Paid Video Streaming Saves Time',
 'Paid Video Streaming Simplifies',
 'Paid Video Streaming Makes Money',
 'Paid Video Streaming Reduce Risk',
 'Paid Video Streaming Organizes',
 'Paid Video Streaming Integrates',
 'Paid Video Streaming Connects',
 'Paid Video Streaming Reduce Effort',
 'Paid Video Streaming Avoid Hassles',
 'Paid Video Streaming Reduce Cost',
 'Paid Video Streaming Quality',
 'Paid Video Streaming Variety',
 'Paid Video Streaming Senses',
 'Paid Video Streaming Informs',
 'Paid Video Streaming Reduce Anxiety',
 'Paid Video Streaming Rewards',
 'Paid Video Streaming Nostalgia',
 'Paid Video Streaming Aesthetics',
 'Paid Video Streaming Badge Value',
 'Paid Video Streaming Wellness',
 'Paid Video Streaming Therapeutic',
 'Paid Video Streaming Fun',
 'Paid Video Streaming Attractiveness',
 'Paid Video Streaming Access',
 'Paid Video Streaming Transcendence',
 'Paid Video Streaming Hope',
 'Paid Video Streaming Actualization',
 'Paid Video Streaming Motivates',
 'Paid Video Streaming Heirloom',
 'Paid Video Streaming Belonging',
 'Crackle rate',
 'Vudu rate',
 'Roku Channel rate',
 'Pluto TV rate',
 'IMDb rate',
 'YouTube rate',
 'Tubi rate',
 'Twitch rate',
 'XUMO rate',
 'Attention 2',
 'Other Free Video Streaming Rate',
 'Other Free Video Streaming Apps',
 'Free Video Streaming Saves Time',
 'Free Video Streaming Simplifies',
 'Free Video Streaming Makes Money',
 'Free Video Streaming Reduce Risk',
 'Free Video Streaming Organizes',
 'Free Video Streaming Integrates',
 'Free Video Streaming Connects',
 'Free Video Streaming Reduce Effort',
 'Free Video Streaming Avoid Hassles',
 'Free Video Streaming Reduce Cost',
 'Free Video Streaming Quality',
 'Free Video Streaming Variety',
 'Free Video Streaming Senses',
 'Free Video Streaming Informs',
 'Free Video Streaming Reduce Anxiety',
 'Free Video Streaming Rewards',
 'Free Video Streaming Nostalgia',
 'Free Video Streaming Aesthetics',
 'Free Video Streaming Badge Value',
 'Free Video Streaming Wellness',
 'Free Video Streaming Therapeutic',
 'Free Video Streaming Fun',
 'Free Video Streaming Attractiveness',
 'Free Video Streaming Access',
 'Free Video Streaming Transcendence',
 'Free Video Streaming Hope',
 'Free Video Streaming Actualization',
 'Free Video Streaming Motivates',
 'Free Video Streaming Heirloom',
 'Free Video Streaming Belonging',
 'Apple Pay rate',
 'Samsung Pay rate',
 'Google Pay rate',
 'Fitbit Pay rate',
 'Garmin Pay rate',
 'LG Pay rate',
 'Other Mobile Pay rate',
 'Other Mobile Pay Apps',
 'Mobile Pay Saves Time',
 'Mobile Pay Simplifies',
 'Mobile Pay Makes Money',
 'Mobile Pay Reduce Risk',
 'Mobile Pay Organizes',
 'Mobile Pay Integrates',
 'Mobile Pay Connects',
 'Mobile Pay Reduce Effort',
 'Mobile Pay Avoid Hassles',
 'Mobile Pay Reduce Cost',
 'Mobile Pay Quality',
 'Mobile Pay Variety',
 'Mobile Pay Senses',
 'Mobile Pay Informs',
 'Mobile Pay Reduce Anxiety',
 'Mobile Pay Rewards',
 'Mobile Pay Nostalgia',
 'Mobile Pay Aesthetics',
 'Mobile Pay Badge Value',
 'Mobile Pay Wellness',
 'Mobile Pay Therapeutic',
 'Mobile Pay Fun',
 'Mobile Pay Attractiveness',
 'Mobile Pay Access',
 'Mobile Pay Transcendence',
 'Mobile Pay Hope',
 'Mobile Pay Actualization',
 'Mobile Pay Motivates',
 'Mobile PayHeirloom',
 'Mobile Pay Belonging',
 'Apple Health rate',
 'Samsung Health rate',
 'Google Fit rate',
 'MyFitnessPal rate',
 'Fitbit Coach rate',
 'Peloton rate',
 'Strava rate',
 'Other Health App rate',
 'Other Health Apps',
 'Health Saves Time',
 'Health Simplifies',
 'Health Makes Money',
 'Health Reduce Risk',
 'Health Organizes',
 'HealthIntegrates',
 'Health Connects',
 'Health Reduce Effort',
 'Health Avoid Hassles',
 'Health Reduce Cost',
 'Health Quality',

In [16]:
for cols in browsers:
    if (("Slate" in cols) | ("Book" in cols) | ('Brand' in cols)):
        print(browsers.columns.get_loc(cols))

6
18
28
29
74
75
76
77
78
80
81
82
83
84
85
86
87
89
90
91
1115
1151
1154
1155
1192
1193
1228
1229

In [25]:
clean_brow = browsers.iloc[:, num.r_[18:19, 83:92]]
clean_brow

,Brand,Top Slate + Accessory,Top Slate Large Display,Top Slate Medium Display,Top Slate Small Display,Top Book Inner Panels,Top Wallet Format,Top Book Outer Panels,Top Book 3 Panels,Top Book Sliding Display
0,Apple,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN
1,Samsung,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,Samsung,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Samsung,NaN,NaN,2.0,NaN,NaN,1.0,NaN,NaN,NaN
4,Apple,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
142,Samsung,NaN,NaN,1.0,NaN,NaN,NaN,2.0,NaN,NaN
143,Samsung,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,Samsung,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
145,Samsung,NaN,NaN,NaN,NaN,1.0,NaN,2.0,NaN,NaN
146,Samsung,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN

In [33]:
totals = []
for cols in clean_brow:
    totals.append(clean_brow[cols].eq(1).sum())
    
for item in totals:
    item = item/145
    print(item)

0.0
0.18620689655172415
0.2413793103448276
0.2413793103448276
0.013793103448275862
0.07586206896551724
0.11724137931034483
0.04827586206896552
0.041379310344827586
0.04827586206896552

In [39]:
clean_brow.loc['Proportions'] = [0.0,
0.18620689655172415,
0.2413793103448276,
0.2413793103448276,
0.013793103448275862,
0.07586206896551724,
0.11724137931034483,
0.04827586206896552,
0.041379310344827586,
0.04827586206896552]

clean_brow.to_excel('browsers.xlsx')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

## Expressers

In [41]:
clean_exp = expressers.iloc[:, num.r_[18:19, 83:92]]
clean_exp

,Brand,Top Slate + Accessory,Top Slate Large Display,Top Slate Medium Display,Top Slate Small Display,Top Book Inner Panels,Top Wallet Format,Top Book Outer Panels,Top Book 3 Panels,Top Book Sliding Display
0,Apple,NaN,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN
1,Apple,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN
2,Other Android (please specify brand),NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
3,Apple,NaN,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN
4,Apple,1.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
284,Samsung,NaN,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN
285,Samsung,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
286,Samsung,NaN,NaN,1.0,NaN,NaN,NaN,NaN,2.0,NaN
287,Samsung,NaN,NaN,1.0,NaN,2.0,NaN,NaN,NaN,NaN
288,Samsung,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,1.0

In [44]:
exp_totals = []
for cols in clean_exp:
    exp_totals.append(clean_exp[cols].eq(1).sum())
    
for item in exp_totals:
    item = item/287
    print(item)

0.0
0.14634146341463414
0.2682926829268293
0.2613240418118467
0.04529616724738676
0.05226480836236934
0.08362369337979095
0.04878048780487805
0.0313588850174216
0.06968641114982578

In [45]:
clean_exp.loc['Proportions'] = [0.0,
0.14634146341463414,
0.2682926829268293,
0.2613240418118467,
0.04529616724738676,
0.05226480836236934,
0.08362369337979095,
0.04878048780487805,
0.0313588850174216,
0.06968641114982578]

clean_exp.to_excel('expressers.xlsx')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

In [57]:
clean_prod = productives.iloc[:, num.r_[18:19, 83:92]]

clean_ss = ss.iloc[:, num.r_[18:19, 83:92]]

clean_trad = traditionalists.iloc[:, num.r_[18:19, 83:92]]

In [59]:
prod_totals = []
for cols in clean_prod:
    prod_totals.append(clean_prod[cols].eq(1).sum())

print("productives")    
for item in prod_totals:
    item = item/len(clean_prod.index)
    print(item)

productives
0.0
0.15527950310559005
0.17701863354037267
0.2422360248447205
0.06521739130434782
0.08385093167701864
0.08074534161490683
0.06521739130434782
0.062111801242236024
0.06832298136645963

In [60]:
ss_totals = []
for cols in clean_ss:
    ss_totals.append(clean_ss[cols].eq(1).sum())

print("ss")    
for item in ss_totals:
    item = item/len(clean_ss.index)
    print(item)

ss
0.0
0.1793103448275862
0.3310344827586207
0.2206896551724138
0.041379310344827586
0.04827586206896552
0.06896551724137931
0.04827586206896552
0.027586206896551724
0.034482758620689655

In [70]:
trad_totals = []
for cols in clean_trad:
    trad_totals.append(clean_trad[cols].eq(1).sum())

print("Traditionalists")    
for item in trad_totals:
    item = item/len(clean_trad.index)
    print(item)

Traditionalists
0.0
0.12371134020618557
0.25773195876288657
0.29896907216494845
0.030927835051546393
0.061855670103092786
0.08247422680412371
0.061855670103092786
0.020618556701030927
0.05154639175257732

In [62]:
clean_prod.loc['Proportions'] = [0.0,
0.15527950310559005,
0.17701863354037267,
0.2422360248447205,
0.06521739130434782,
0.08385093167701864,
0.08074534161490683,
0.06521739130434782,
0.062111801242236024,
0.06832298136645963]


clean_ss.loc['Proportions'] = [0.0,
0.1793103448275862,
0.3310344827586207,
0.2206896551724138,
0.041379310344827586,
0.04827586206896552,
0.06896551724137931,
0.04827586206896552,
0.027586206896551724,
0.034482758620689655]


clean_trad.loc['Proportions'] = [0.0,
0.125,
0.2604166666666667,
0.3020833333333333,
0.03125,
0.0625,
0.08333333333333333,
0.0625,
0.020833333333333332,
0.052083333333333336]



clean_prod.to_excel('productives.xlsx')
clean_ss.to_excel('social_savies.xlsx')
clean_trad.to_excel('traditionalists.xlsx')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_with_indexer(indexer, value)

## Second Place

In [67]:
totals = []
for cols in clean_brow:
    totals.append(clean_brow[cols].eq(2).sum())

print('Browsers')
for item in totals:
    item = item/len(clean_brow.index)
    print(item)

Browsers
0.0
0.11486486486486487
0.20270270270270271
0.16216216216216217
0.02027027027027027
0.14189189189189189
0.10810810810810811
0.10810810810810811
0.060810810810810814
0.07432432432432433

In [68]:
exp_totals = []
for cols in clean_exp:
    exp_totals.append(clean_exp[cols].eq(2).sum())
    
    
print('Expressers') 
for item in exp_totals:
    item = item/len(clean_exp.index)
    print(item)

Expressers
0.0
0.15172413793103448
0.17586206896551723
0.11724137931034483
0.041379310344827586
0.15862068965517243
0.09655172413793103
0.1103448275862069
0.04827586206896552
0.09655172413793103

In [66]:
prod_totals = []
for cols in clean_prod:
    prod_totals.append(clean_prod[cols].eq(2).sum())

print("productives")    
for item in prod_totals:
    item = item/len(clean_prod.index)
    print(item)

productives
0.0
0.14860681114551083
0.16408668730650156
0.1393188854489164
0.05263157894736842
0.13312693498452013
0.07120743034055728
0.10526315789473684
0.05572755417956656
0.12693498452012383

In [69]:
ss_totals = []
for cols in clean_ss:
    ss_totals.append(clean_ss[cols].eq(2).sum())

print("ss")    
for item in ss_totals:
    item = item/len(clean_ss.index)
    print(item)

ss
0.0
0.14383561643835616
0.1643835616438356
0.17123287671232876
0.03424657534246575
0.0958904109589041
0.07534246575342465
0.15753424657534246
0.02054794520547945
0.13013698630136986

In [71]:
trad_totals = []
for cols in clean_trad:
    trad_totals.append(clean_trad[cols].eq(2).sum())

print("traditionalists")    
for item in trad_totals:
    item = item/len(clean_trad.index)
    print(item)

traditionalists
0.0
0.08247422680412371
0.1958762886597938
0.15463917525773196
0.10309278350515463
0.13402061855670103
0.07216494845360824
0.061855670103092786
0.020618556701030927
0.16494845360824742

In [74]:
clean_brow.loc['Proportions (2nd)'] = [0.0,
0.11486486486486487,
0.20270270270270271,
0.16216216216216217,
0.02027027027027027,
0.14189189189189189,
0.10810810810810811,
0.10810810810810811,
0.060810810810810814,
0.07432432432432433]

clean_exp.loc['Proportions (2nd)'] = [0.0,
0.15172413793103448,
0.17586206896551723,
0.11724137931034483,
0.041379310344827586,
0.15862068965517243,
0.09655172413793103,
0.1103448275862069,
0.04827586206896552,
0.09655172413793103]

clean_prod.loc['Proportions (2nd)'] = [0.0,
0.14860681114551083,
0.16408668730650156,
0.1393188854489164,
0.05263157894736842,
0.13312693498452013,
0.07120743034055728,
0.10526315789473684,
0.05572755417956656,
0.12693498452012383]


clean_ss.loc['Proportions (2nd)'] = [0.0,
0.14383561643835616,
0.1643835616438356,
0.17123287671232876,
0.03424657534246575,
0.0958904109589041,
0.07534246575342465,
0.15753424657534246,
0.02054794520547945,
0.13013698630136986]

clean_trad.loc['Proportions (2nd)'] = [0.0,
0.08247422680412371,
0.1958762886597938,
0.15463917525773196,
0.10309278350515463,
0.13402061855670103,
0.07216494845360824,
0.061855670103092786,
0.020618556701030927,
0.16494845360824742]



clean_brow.to_excel('browsers2.xlsx')
clean_exp.to_excel('expressers2.xlsx')
clean_prod.to_excel('productives2.xlsx')
clean_ss.to_excel('social_savies2.xlsx')
clean_trad.to_excel('traditionalists2.xlsx')

/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:965: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s